### ISSUE TITLE
svgwrite Module dependency added without any notifications

### ISSUE THREAD

**Issue by jayrambhia** [sightmachine/SimpleCV#564]
I updated my develop branch and was troubled with the following error.

``` python

ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/simplecv", line 9, in <module>
    load_entry_point('SimpleCV==1.3', 'console_scripts', 'simplecv')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/jay/SimpleCV/SimpleCV/__init__.py", line 4, in <module>
    from SimpleCV.Camera import *
  File "/home/jay/SimpleCV/SimpleCV/Camera.py", line 5, in <module>
    from SimpleCV.ImageClass import Image, ImageSet, ColorSpace
  File "/home/jay/SimpleCV/SimpleCV/ImageClass.py", line 14497, in <module>
    from SimpleCV.DrawingLayer import *
  File "/home/jay/SimpleCV/SimpleCV/DrawingLayer.py", line 5, in <module>
    import svgwrite
ImportError: No module named svgwrite

```

It seems that `svgwrite` module is required. It was added in this commit https://github.com/sightmachine/SimpleCV/commit/3d473c5798c03f03c07ccfb7ab70bc03669f07e7 

Addition of a new dependency should have been notified and added in setup.

**Comment by anthonyattard** [comment]
Still getting this error.
