### ISSUE TITLE
Raspberry Pi setup

### ISSUE THREAD

**Issue by matrhint** [sightmachine/SimpleCV#669]
The instructions need to have "sudo pip install svgwrite" added to step 4.

**Comment by goldenbucks** [comment]
why do you need SVG drawings. ??

**Comment by MoshiBin** [comment]
Confirmed, when installing on Raspbian 2015-05-05, the {simplecv} command complains about missing svgwrite:

```
pi@raspberrypi ~ $ simplecv 
ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/simplecv", line 9, in <module>
    load_entry_point('SimpleCV==1.3', 'console_scripts', 'simplecv')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV/__init__.py", line 4, in <module>
    from SimpleCV.Camera import *
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV/Camera.py", line 5, in <module>
    from SimpleCV.ImageClass import Image, ImageSet, ColorSpace
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV/ImageClass.py", line 14768, in <module>
    from SimpleCV.DrawingLayer import *
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV/DrawingLayer.py", line 5, in <module>
    import svgwrite
ImportError: No module named svgwrite
```

**Comment by LeoFNaN** [comment]
Just adding that I got the same error with Raspbian Jessie - 09/24/15 - Kernel version: 4.1.  

Here it is in action: 
![simplecv-svg-error](https://cloud.githubusercontent.com/assets/8132772/11299740/1735bed6-8f3e-11e5-9b0b-8559c2217de7.jpg)

**Comment by rodgomesc** [comment]
you installed svgwrite?

``` 
sudo pip install svgwrite
```

**Comment by yaroshiroki** [comment]
any fixes to this issue?

**Comment by rodgomesc** [comment]
@yaroshiroki the last commit was more than 4 years ago, this project seems to be dead

**Comment by jairoareyes** [comment]
Hi, I have the same problem, did you get solve it? thanks. @MoshiBin @rodgomesc

**Comment by yaroshiroki** [comment]
Hi, I’m afraid not. I believe the main source of the issue is that all of
simplecv works with python 2, not 3. The best thing to do in my opinion is
to switch to OpenCV instead, I can link you some nice repositories for
computer vision.
Best of luck, Yaro Shiroki.
