### ISSUE TITLE
Can't lpad OpenCV library which is required by SimpleCV

### ISSUE THREAD

**Issue by ramwin** [sightmachine/SimpleCV#685]
[#7#wangx@wangxiang-PC:~]$sudo apt-get install python-scipy python-numpy python-pygame python-setuptools python-pip python-opencv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-opencv is already the newest version.
python-pygame is already the newest version.
python-scipy is already the newest version.
python-numpy is already the newest version.
python-setuptools is already the newest version.
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[#8#wangx@wangxiang-PC:~]$simplecv
Traceback (most recent call last):
  File "/usr/local/bin/simplecv", line 9, in <module>
    load_entry_point('SimpleCV==1.3', 'console_scripts', 'simplecv')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV-1.3-py2.7.egg/SimpleCV/__init__.py", line 3, in <module>
    from SimpleCV.base import *
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV-1.3-py2.7.egg/SimpleCV/base.py", line 59, in <module>
    raise ImportError("Cannot load OpenCV library which is required by SimpleCV")
ImportError: Cannot load OpenCV library which is required by SimpleCV

ubuntu:14.04
python:2.7.6

**Comment by ramwin** [comment]
I create a new virtual machine. And do the same thing, I can import cv2.cv in the virtual machine, but I can't import cv2.cv on my self computer. I tried to uninstall python-opencv and reinstall python-opencv, but it didn't work ethier.

**Comment by ramwin** [comment]
My cv2's version is 3.1.0, and the cv2 in the virtual machine is 2.4.8. It seems that we can't import cv2.cv in the latest Opencv version. But the SimpleCV is using the cv. Is there any thins I miss or just because the SimpleCV can't support the latest python-opencv?  I'm using SimpleCV 1.3.0

**Comment by kaush-rasto** [comment]
I am also facing same issue . 
I installed simpleCV from the superpack and get the same error after installation . 

Platform : Windows 
Python : 2.7.6

**Comment by wilsontov** [comment]
Here too! :/

```
Traceback (most recent call last):
  File "background.py", line 10, in <module>
    from SimpleCV import *
  File "/Library/Python/2.7/site-packages/SimpleCV-1.3-py2.7.egg/SimpleCV/__init__.py", line 3, in <module>
    from SimpleCV.base import *
  File "/Library/Python/2.7/site-packages/SimpleCV-1.3-py2.7.egg/SimpleCV/base.py", line 59, in <module>
    raise ImportError("Cannot load OpenCV library which is required by SimpleCV")
ImportError: Cannot load OpenCV library which is required by SimpleCV
```

**Comment by bgth** [comment]
Please try installing opencv 2.4.
