### ISSUE TITLE
Can't install SimpleCV on RPi3

### ISSUE THREAD

**Issue by Villafruela** [sightmachine/SimpleCV#701]
Hi
i'm trying to install SimpleCV on a RPi 3.

After: 
sudo apt-get install ipython python-opencv python-scipy python-numpy python-setuptools python-pip
And:
sudo pip install https://github.com/sightmachine/SimpleCV/zipball/master

When launching simplecv, i get:
```
Traceback (most recent call last):
  File "/usr/local/bin/simplecv", line 11, in <module>
    load_entry_point('SimpleCV==1.3', 'console_scripts', 'simplecv')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/SimpleCV/__init__.py", line 3, in <module>
    from SimpleCV.base import *
  File "/usr/local/lib/python3.4/dist-packages/SimpleCV/base.py", line 198
    print 'unit test'
                    ^
SyntaxError: Missing parentheses in call to 'print'
```
It looks like the installation is done on python 3 although it needs to run through python2.x (the print 'unit test' is 2.x, for P3 i should have print('unit test')

Am i the only one getting this?

How can i fix it please ?

**Comment by michbil** [comment]
@Villafruela i believe you should run ```sudo pip2 install```

**Comment by Villafruela** [comment]
Hi @michbil,

Tried it, doesn't work...

**Comment by michbil** [comment]
@Villafruela try second method without pip. 
```
mkdir ~/Code
cd ~/Code
git clone git://github.com/sightmachine/SimpleCV.git
cd SimpleCV
sudo pip2 install -r requirements.txt
sudo python2 setup.py develop
```
I successfully installed simplecv on Rpi3, but when trying tostart it getting
```pygame parachute deployed(Segmentating fault)``` error. Still have not idea what to do with it

**Comment by mickey9801** [comment]
I have the same issue and tried install from source. But while running "sudo pip install -r requirements.txt" I got an error "Could not find any downloads that satisfy the requirement PIL (from -r requirements.txt (line 3))". Seem that PIL is no longer available.

Finally I install Pillow and all libraries listed in requirements.txt manually. Then run “sudo python setup.py develop” to install.

    $ mkdir ~/Code
    $ cd ~/Code
    $ git clone git://github.com/sightmachine/SimpleCV.git
    $ cd SimpleCV
    $ cat requirements.txt #Install required libraries manually
    $ sudo pip install svgwrite
    $ sudo pip install pillow
    $ sudo python setup.py develop

**Comment by wilsontov** [comment]
Try installing with .deb file, if you can.

**Comment by Hwzsnow** [comment]
@Villafruela    me too
Do you know how to install it?

**Comment by jairoareyes** [comment]
Hi, I have the same problem, what is the final solution?
