### ISSUE TITLE
Missing parentheses problems at SimpleCV import

### ISSUE THREAD

**Issue by szg0000** [sightmachine/SimpleCV#705]
Traceback (most recent call last):
  File "simplecv.py", line 2, in <module>
    from SimpleCV import Camera
  File "/usr/local/lib/python3.6/site-packages/SimpleCV/__init__.py", line 3, in <module>
    from SimpleCV.base import *
  File "/usr/local/lib/python3.6/site-packages/SimpleCV/base.py", line 139
    print 'unit test'
                    ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by rodgomesc** [comment]
You don't know how programm In python3? please use parentheses in you
print, please learn, Python 3 for Absolute Beginners, before SimpleCV

Em sex, 7 de jul de 2017 17:38, szg0000 <notifications@github.com> escreveu:

**Comment by rodgomesc** [comment]
I'm not sure, but I think SimpleCV does not support Python3

**Comment by pawarpooja** [comment]
@szg0000.. Have you got any solution for that problem?? Actually i am also facing the same issue..

**Comment by mananshukla6** [comment]
Can you guys welcome me to your club as well? 
Do we have the solution to this as of now??
