### ISSUE TITLE
memoryerror

### ISSUE THREAD

**Issue by slanning6** [sightmachine/SimpleCV#709]
Could you please help?
I am trying to load SimpleCV

I run the gethub http and it erros out:

Terminal input/output:

pi@raspberrypi:~ $ sudo pip install https://github.com/sightmachine/SimpleCV/zipball/master
Collecting https://github.com/sightmachine/SimpleCV/zipball/master
  Downloading https://github.com/sightmachine/SimpleCV/zipball/master
     | 53.8MB 1.3MB/sException:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 605, in _download_url
    consume(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 870, in consume
    deque(iterator, maxlen=0)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 428, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 590, in read_chunked
    self._update_chunk_length()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 106, in _update_chunk_length
    self._fp._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

**Comment by slanning6** [comment]
Hi,
If anyone can help on this.. I am working on barcode scanning. This issue is giving me a brick wall.
Help me please!

**Comment by raspberrypieman** [comment]
Hi,
  Sorry I cannot help - I am getting exactly the same Memory Error. I am using a clean install of Raspbian Stretch.
I hope someone is reading these issues, who can help.

**Comment by keefo149** [comment]
Try this site and download manualy , it worked for me

http://simplecv.readthedocs.io/en/latest/HOWTO-Install%20on%20RaspberryPi.html

mkdir ~/Code
cd ~/Code
git clone git://github.com/sightmachine/SimpleCV.git
cd SimpleCV
sudo pip install -r requirements.txt
sudo python setup.py develop

**Comment by bcopy** [comment]
@keefo149 : if we do what you suggest, we get 

Collecting PIL (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement PIL (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for PIL (from -r requirements.txt (line 3))

We are on raspbian stretch.

**Comment by Chris-DeH** [comment]
Same problem(s) here - MemoryError and cannot do the manual download.

Raspberry Pi3 with Stretch

**Comment by wenyongshuang** [comment]
I am getting  the same Memory Error too.

pi@raspberrypi:~ $ sudo pip install https://github.com/sightmachine/SimpleCV/zipball/master
Collecting https://github.com/sightmachine/SimpleCV/zipball/master
  Downloading https://github.com/sightmachine/SimpleCV/zipball/master
     | 53.8MB 7.9MB/sException:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 605, in _download_url
    consume(downloaded_chunks)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 870, in consume
    deque(iterator, maxlen=0)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 428, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 590, in read_chunked
    self._update_chunk_length()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 106, in _update_chunk_length
    self._fp._close()
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError 
help please   !

**Comment by shakeeltariq** [comment]
Faced the same issue... solved by adding --no-cache-dir to the pip install:

`sudo pip install https://github.com/sightmachine/SimpleCV/zipball/master --no-cache-dir`

**Comment by mUtterberg** [comment]
@shakeeltariq THANK YOU. That saved my rpi build.
