### ISSUE TITLE
Cannot load OpenCV library,

### ISSUE THREAD

**Issue by snow-frog** [sightmachine/SimpleCV#721]
Installed on linux mint from here, openCV 3.2
Upon entering simplecv command, failure 
`Traceback (most recent call last):
  File "/usr/local/bin/simplecv", line 11, in <module>
    load_entry_point('SimpleCV==1.3', 'console_scripts', 'simplecv')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV-1.3-py2.7.egg/SimpleCV/__init__.py", line 3, in <module>
    from SimpleCV.base import *
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV-1.3-py2.7.egg/SimpleCV/base.py", line 60, in <module>
    raise ImportError("Cannot load OpenCV library which is required by SimpleCV")
ImportError: Cannot load OpenCV library which is required by SimpleCV
`

**Comment by MokeEire** [comment]
I am getting the same ImportError on a Raspberry Pi
